### ISSUE TITLE
Check dependency loop logic is incorrect

### ISSUE THREAD

**Issue by alexby** [ZitRos/node-graceful-shutdown#4]
The `checkDependencyLoop` logic is incorrect. Even the exampled code doesn't work:
```
onShutdown("http-server", async function () {
    // Stop your http server here.
});
// module2.js
onShutdown("message-bus", ["http-server"], async function () {
    // Close your RabbitMQ connection here ONLY AFTER http server's onShutdown completed.
});
// moduleX.js
onShutdown("database", ["http-server", "message-bus"], async function () {
    // Shut down your database here, ONLY AFTER http-server and message-bus are completed.
});
```
You should have independent `visited` list for each recursion branch.

**Comment by nikitaeverywhere** [comment]
I knew someone will notice it! Thanks for reporting :) It's my 2-year-old quick shutdown implementation, where the actual implementation was the "layered" logic instead of a tree one. And it's true that the order of functions in the example is not quite correct (`database` and `message-bus` appear on the same layer). However, for simple dependencies between shutdown functions it works flawlessly.

I'll fix it shortly, thanks for highlighting the issue.

**Comment by nikitaeverywhere** [comment]
Now fixed. The new `1.1.0` release is published.

As I see more and more people using this package, I can't keep this opened :) Thanks for discovering it!

![image](https://user-images.githubusercontent.com/4989256/97122284-717e4580-172d-11eb-91e8-ffe3dbb642b2.png)
